on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
    
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '17'
        cache: 'gradle'
    - name: Lint
      run: ./gradlew lintKotlin lint
    - name: Run tests
      run: ./gradlew testDebug --continue
