on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
        cache: 'gradle'
    - name: Lint
      run: ./gradlew lintKotlin lint
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
        cache: 'gradle'
    - name: Run tests
      run: ./gradlew testDebug --continue
  androidtest:
    runs-on: macos-12 # For virtualization support
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
        cache: 'gradle'
    - name: Run instrumented tests
      run: | # https://github.com/android/sunflower/blob/e404b8c310d9b9199dd1d74d58072f4116d380f2/.github/workflows/android.yml#L66
        ./gradlew pixel6api33DebugAndroidTest \
          -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" \
          -Pandroid.experimental.testOptions.managedDevices.setupTimeoutMinutes=20 \
          -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true \
          --info
    - uses: actions/upload-artifact@v3
      with:
        name: outputs
        path: app/build/reports/
